AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - "spec/dummy/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
