require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - "spec/dummy/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Naming/FileName:
  Exclude:
    - 'lib/tokenable-ruby.rb'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/LineLength:
  Max: 150
  Exclude:
    - "spec/**/*"

Lint/EmptyBlock:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/ClassVars:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitBlockExpectation:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false
